#apiVersion: networking.k8s.io/v1
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-deployment
  labels:
    app: product-service-deployment
spec:
  selector:
    matchLabels:
      app: product-service-deployment
  replicas: 2    
  template:
  
    metadata:
      labels:
        app: product-service-deployment
    spec:
      containers:
        - name: product-service-container
          image: kuldeepkm/sample-shopping-app-product-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "0.1"
          ports:
            - containerPort: 3000
          env:
            - name: SEC_DBUSER
              valueFrom:
                secretKeyRef: 
                  name:  app-secrets
                  key: SEC_DBUSER
            - name: SEC_DBPASS
              valueFrom:
                secretKeyRef: 
                  name:  app-secrets
                  key: SEC_DBPASS
            - name: DBURL
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db-service
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db-port
            - name: DBNAME
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: db-name
            - name: PRODUCT_IMAGE_SRV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: product_image_url
            - name: PRODUCT_IMAGE_HOST
              value: http://$(PRODUCT_IMAGE_SRV)/
                  
            - name: MONGO_URI
              value: mongodb://$(SEC_DBUSER):$(SEC_DBPASS)@$(DBURL):$(DBPORT)/$(DBNAME)?authSource=admin
            - name: TLS
              value: "0"


---
apiVersion: v1
kind: Service
metadata:
  name: product-service-service
spec:
  type: LoadBalancer
  # externalTrafficPolicy: Local
  selector:
    app: product-service-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30011